import { NextRequest, NextResponse } from "next/server"
import prisma from "@/lib/prisma"
import { getCurrentUser } from "@/lib/auth/session"
import { hasPermission } from "@/lib/auth/password"
import { SoarClient, SoarArtifact } from "@/lib/api/soar"

function toCredentialsObject(raw: unknown): Record<string, any> {
  if (!raw) return {}
  if (Array.isArray(raw)) {
    const out: Record<string, any> = {}
    for (const item of raw) {
      if (
        item &&
        typeof item === "object" &&
        "key" in item &&
        "value" in item &&
        typeof (item as any).key === "string"
      ) {
        out[(item as any).key] = (item as any).value
      }
    }
    return out
  }
  if (typeof raw === "object") return raw as Record<string, any>
  return {}
}

function readSoarConfigFromIntegration(integration: any): {
  host: string
  orgId: string
  keyId: string
  keySecret: string
} {
  const credentials = toCredentialsObject(integration?.credentials)

  // Prefer credentials fields first to avoid stale dedicated columns when integration was edited before client regen.
  const host = String(credentials.soar_host || integration?.soarHost || "").trim()
  const orgId = String(credentials.soar_org_id || integration?.soarOrgId || "").trim()
  const keyId = String(credentials.soar_key_id || integration?.soarKeyId || credentials.SOAR_KEY_ID || "").trim()
  const keySecret = String(
    credentials.soar_key_secret || integration?.soarKeySecret || credentials.SOAR_KEY_SECRET || "",
  ).trim()

  return { host, orgId, keyId, keySecret }
}

function buildIncidentPayload(alert: any) {
  const alertTitle = String(alert?.title || "QRadar Offense")
  const offenseId = alert?.metadata?.qradar?.id
  const sourceIp = String(
    alert?.metadata?.qradar?.sourceip ||
      alert?.metadata?.qradar?.offense_source ||
      alert?.metadata?.sourceip ||
      "",
  ).trim()
  const compactTitle = alertTitle.replace(/\s+/g, " ").trim()
  const severity = alert?.severity || alert?.metadata?.qradar?.severity || "Unknown"
  const description = [
    `Generated by SOC Dashboard`,
    `Alert ID: ${alert.id}`,
    offenseId ? `Offense ID: ${offenseId}` : null,
    `Severity: ${severity}`,
    alert?.description ? `Description: ${alert.description}` : null,
  ]
    .filter(Boolean)
    .join("\n")

  // Do NOT include 'id' field — SOAR auto-assigns incident IDs globally.
  return {
    name: offenseId
      ? `QRadar ID ${offenseId} , ${compactTitle}${sourceIp ? ` - ${sourceIp}` : ""}`
      : `${compactTitle}${sourceIp ? ` - ${sourceIp}` : ""}`,
    discovered_date: Date.now(),
    create_date: Date.now(),
    plan_status: "A",
    description: {
      format: "text" as const,
      content: description,
    },
  }
}

function buildArtifacts(alert: any): SoarArtifact[] {
  const qradar = (alert?.metadata?.qradar as any) || {}
  const artifacts: SoarArtifact[] = []

  const seenIps = new Set<string>()

  function addIp(value: string, label: string) {
    const ip = value?.trim()
    if (!ip || seenIps.has(ip)) return
    // Basic IP validation (v4 or v6)
    if (!/^[\d.a-fA-F:]+$/.test(ip)) return
    seenIps.add(ip)
    artifacts.push({
      type: { name: "IP Address" },
      value: ip,
      description: { format: "text", content: label },
    })
  }

  // Source IP
  const sourceIp = String(qradar.sourceip || qradar.offense_source || "").trim()
  if (sourceIp) addIp(sourceIp, "Source IP from QRadar offense")

  // Destination IPs — stored as comma/space-separated string or array
  const destRaw = qradar.destination_networks || qradar.local_destination_addresses || qradar.destination_ips || ""
  const destList: string[] = Array.isArray(destRaw)
    ? destRaw.map(String)
    : String(destRaw)
        .split(/[,\s]+/)
        .filter(Boolean)
  for (const ip of destList) addIp(ip, "Destination IP from QRadar offense")

  // Offense ID as a string artifact
  const offenseId = qradar.id ?? qradar.offense_id
  if (offenseId != null) {
    artifacts.push({
      type: { name: "String" },
      value: String(offenseId),
      description: { format: "text", content: "QRadar Offense ID" },
    })
  }

  // Username / account if present
  const username = String(qradar.username || qradar.user_name || "").trim()
  if (username) {
    artifacts.push({
      type: { name: "String" },
      value: username,
      description: { format: "text", content: "Username from QRadar offense" },
    })
  }

  // Log source name
  const logSource = String(qradar.log_source_name || qradar.log_sources || "").trim()
  if (logSource) {
    artifacts.push({
      type: { name: "String" },
      value: logSource,
      description: { format: "text", content: "Log source" },
    })
  }

  return artifacts
}

function buildIncidentSummary(incident: any) {
  if (!incident || typeof incident !== "object") {
    return null
  }

  return {
    id: incident.id ?? null,
    name: incident.name ?? null,
    plan_status: incident.plan_status ?? null,
    create_date: incident.create_date ?? null,
    discovered_date: incident.discovered_date ?? null,
    severity_code: incident.severity_code ?? null,
    owner_id: incident.owner_id ?? null,
    phase_id: incident.phase_id ?? null,
    vers: incident.vers ?? null,
  }
}

export async function POST(request: NextRequest) {
  try {
    const user = await getCurrentUser()
    if (!user) {
      return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 })
    }

    if (!hasPermission(user.role, "update_alert_status")) {
      return NextResponse.json(
        { success: false, error: "Forbidden: You don't have permission to send alert to SOAR" },
        { status: 403 },
      )
    }

    const body = await request.json()
    const alertId = String(body?.alertId || "").trim()
    const explicitOrgId = body?.orgId ? String(body.orgId).trim() : ""

    if (!alertId) {
      return NextResponse.json({ success: false, error: "Missing alertId" }, { status: 400 })
    }

    const alert = await prisma.alert.findUnique({
      where: { id: alertId },
      include: { integration: true },
    })

    if (!alert) {
      return NextResponse.json({ success: false, error: "Alert not found" }, { status: 404 })
    }

    if (alert.integration?.source !== "qradar") {
      return NextResponse.json(
        { success: false, error: "SOAR send is only supported for QRadar integration" },
        { status: 400 },
      )
    }

    const baseSoar = readSoarConfigFromIntegration(alert.integration)
    const targetOrgId = String(explicitOrgId || baseSoar.orgId).trim()

    if (!baseSoar.host || !baseSoar.keyId || !baseSoar.keySecret || !targetOrgId) {
      return NextResponse.json(
        {
          success: false,
          error:
            "Missing SOAR credentials. Required: soar_host, soar_org_id, soar_key_id, soar_key_secret in QRadar integration.",
        },
        { status: 400 },
      )
    }

    if (explicitOrgId && explicitOrgId !== baseSoar.orgId) {
      return NextResponse.json(
        {
          success: false,
          error: `Selected orgId ${targetOrgId} does not match integration org_id ${baseSoar.orgId}`,
        },
        { status: 400 },
      )
    }

    const soarClient = new SoarClient({
      host: baseSoar.host,
      keyId: baseSoar.keyId,
      keySecret: baseSoar.keySecret,
    })

    let availableOrgs: Array<{ id: string; name?: string }> = []
    try {
      availableOrgs = await soarClient.getOrganizations()
      const orgExists = availableOrgs.some((org) => org.id === targetOrgId)
      if (!orgExists) {
        return NextResponse.json(
          {
            success: false,
            error: `Configured SOAR org_id ${targetOrgId} is not found on host ${baseSoar.host}`,
            details:
              availableOrgs.length > 0
                ? `Available org IDs: ${availableOrgs.map((o) => o.id).join(", ")}`
                : "SOAR returned no organizations for this API key",
          },
          { status: 400 },
        )
      }
    } catch (orgError: any) {
      console.warn("[SOAR Send] Organization pre-check failed, continuing with direct incident create", orgError)
    }

    const integrationConfig = (alert.integration.config as any) || {}

    // Let SOAR auto-assign the incident ID — do not predict or send an id in the payload.
    const payload = buildIncidentPayload(alert)
    const createResult = await soarClient.createIncident(targetOrgId, payload)

    // Read the actual incident ID assigned by SOAR from the response.
    const usedIncidentId: number = Number(createResult?.id ?? createResult?.incident_id ?? 0)

    // Add artifacts (source IP, dest IPs, offense ID, username, etc.) — non-fatal if it fails.
    if (usedIncidentId > 0) {
      const artifacts = buildArtifacts(alert)
      if (artifacts.length > 0) {
        await soarClient.addArtifacts(targetOrgId, usedIncidentId, artifacts)
      }
    }

    const nextConfig = {
      ...integrationConfig,
      soar_last_incident_id: usedIncidentId,
      soar_last_synced_at: new Date().toISOString(),
    }

    const existingMetadata = (alert.metadata as any) || {}
    const nextMetadata = {
      ...existingMetadata,
      soar: {
        ...(existingMetadata.soar || {}),
        sent: true,
        incident_id: usedIncidentId,
        org_id: targetOrgId,
        sent_at: new Date().toISOString(),
        incident_details: buildIncidentSummary(createResult),
      },
    }

    await prisma.$transaction([
      prisma.integration.update({
        where: { id: alert.integrationId },
        data: { config: nextConfig },
      }),
      prisma.alert.update({
        where: { id: alert.id },
        data: { metadata: nextMetadata },
      }),
      prisma.alertTimeline.create({
        data: {
          alertId: alert.id,
          eventType: "soar_send",
          description: `Sent to SOAR org ${targetOrgId} with incident ID ${usedIncidentId}`,
          oldValue: "",
          newValue: String(usedIncidentId),
          changedBy: user.name || user.email || "System",
          changedByUserId: user.userId,
          timestamp: new Date(),
        },
      }),
    ])

    return NextResponse.json({
      success: true,
      data: {
        orgId: targetOrgId,
        incidentId: usedIncidentId,
        incident: buildIncidentSummary(createResult),
        response: createResult,
      },
    })
  } catch (error: any) {
    console.error("[SOAR Send] Error sending offense to SOAR:", error)
    return NextResponse.json(
      {
        success: false,
        error: "Failed to send offense to SOAR",
        details: error?.message || "Unknown error",
      },
      { status: 500 },
    )
  }
}
